### ISSUE TITLE
Spineomatic Template Won't Save

### ISSUE THREAD

**Issue by jbhintz** [ExLibrisGroup/spineomatic-cloudapp#121]
I'm a new user to SpineOMatic. I want to print barcode labels using Alma. I create a new template. I click Save and it circles endlessly without saving. Any suggestions?

**Comment by mgobat** [comment]
Hi @jbhintz. Sorry you have having issues saving your template. We have not heard of this issue previously. Could you provide the details of what you are including in your template; fields, text formatting, all the options, etc. Before clicking "Save", click the "..." button in the toolbar, then the "<>" button. This will show you the HTML source code for your template. Please copy the source code and paste it into a text file on your computer. Then attach that text file to your post here. Thanks.

**Comment by mgobat** [comment]
@jbhintz, also are you using a Windows, Mac, or Chromebook and which web browser? Thanks.

**Comment by DiederikLA** [comment]
Hi @mgobat ,

We are experiencing the same problem in our Alma environment. My colleagues reported that they could no longer save changes to templates. The problem does not seem related to the validity/consistency of the HTML source code: even if they opened an existing template and tried to save it without introducing any changes, the 'save'-circle keeps on turning. 
It rather appears to be a problem of autorization: I'm working with an admin-account with extensive autorization and have no problems saving new or changed templates. I do not find any trace in the documentations about the (changes in) necessary roles to work with SpineOMatic Cloud App in Alma. But maybe this can help you to find what is going wrong.

Best regards, 

Diederik

**Comment by mgobat** [comment]
@DiederikLA, thank you for that additional information. We will investigate.

**Comment by mgobat** [comment]
Hi @DiederikLA. When did this problem begin? Was it with the March release, or was it working fine with March and started happening later? Are you using the production version of the SpineOMatic Cloud App (v1.3.5) or the beta version (v1.3.6-beta)?
The production version hasn't changed since 2023-August, so if that's the version you are using, the problem is likely on the Alma back-end....so yes, please open a Salesforce case.

**Comment by DiederikLA** [comment]
Hi @mgobat . I received a first message in our internal helpdesk on March 21 so well after the March release. I can ask my colleague whether at that time he hadn't used SpineOMatic for a long time. 

I did the testing on v1.3.5 and so I will open a Salesforce case to see what might by the problem at Alma-side.

Many thanks for your quick reaction. 

Diederik

**Comment by mgobat** [comment]
@jbhintz, @DiederikLA. I believe this is working as designed, to some degree. The "Configuration" option should not appear if the logged in user does not have the "General Administrator" privilege in Alma. Note that the configuration icon (wrench) does not appear in the "..." menu of the SpineOMatic Cloud App when the user does not have "General Administrator". So that fact that the Cloud App is showing the "Configuration" button is a bug; when the wrench does not appear in the "..." menu, the "Configuration" button should not appear. 

Please see this page specific to the SpineOMatic Cloud App that indicates the user must have "General Administrator" in order to configure the Cloud App.

https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#configuration

@jbhintz, please check if the configuration icon (wrench) appears in the "..." menu at the top of the SpineOMatic Cloud App. If it does not, then it is likely that the logged in user doesn't have General Administrator privileges and that's why you get the spinning circle when trying to save the template.

@DiederikLA. thanks for your debugging work finding the "General Administrator" issue.

**Comment by DiederikLA** [comment]
Hi @mgobat , many thanks for clearing this out.

We will certainly talk to Ex Libris about the link between the role of General System Administrator (which is more or less an "all options open" role) and the authorization to configure layouts and templates in SpineOMatic. In our consortium we have hundreds of libraries, with almost as many label designs. It would be a very bad idea to give the role to a large number of colleagues and, on the other hand, I'm not inclined to limit this job to a very small number of staff accounts who would become responsible for all these minor changes. 

Best regards, 

Diederik Lanoye

**Comment by jbhintz** [comment]
Hi @mgobat, I have closing duties today, so my arrival time to work is late morning. Or I would have replied to you before now.

**Comment by mgobat** [comment]
@jbhintz, thanks for the additional information.

The SpineOMatic Cloud App is currently checking for either the "Catalog Administrator" or "General Administrator" role. If the logged in user has either of these, the "Configuration" button should appear, but the wrench icon in the "..." menu should only display for those with "General Administrator". @jbhintz, I'm guessing you have the "Catalog Administrator" role, but not the "General Administrator" role. The problem here is that the save of the configuration is being blocked if the logged in user only has "Catalog Administrator". We are investigating.

@DiederikLA, @jbhintz, for our own education, which roles do you think are appropriate for an Alma user to have in order to configure templates and layouts in the SpineOMatic Cloud App?

**Comment by DiederikLA** [comment]
@mgobat , it seems to me that something has changed because we were aware that to have configuration rights for SpineOMatic at least the role of Catalog administrator was required. Therefore, all colleagues within our consortium (KU Leuven, Belgium) who are responsible for handling the physical collections in their libraries have also been given that role. So until now, with this role, they could not only see the configuration button but also make and save changes.

So as far as we are concerned, the link between the Catalog Administrator role and configuration rights in SpineOMatic is ok.

**Comment by mgobat** [comment]
@DiederikLA, we have a fix coming in the Alma April release that will permit users with "Catalog Administrator" role to once again be able to successfully update the SpineOMatic Cloud App configuration.

**Comment by DiederikLA** [comment]
Hi @mgobat , the problem has indeed been fixed perfectly and everything is back as it was before. Many thanks for your help!

Diederik
