### ISSUE TITLE
Labels can only be printed to label sheets and not to a label printer

### ISSUE THREAD

**Issue by MaggieMcGee** [ExLibrisGroup/spineomatic-cloudapp#6]
Currently, SpineOmatic cloud app can only print labels using sheets of labels. It does not have the ability to print to a label printer such as Zebra printers. It would be nice to have the option to choose to print using a label printer or using label sheets. Example is Orbis Cascades Label Printer App prints to a label printer, but not to label sheets.

**Comment by dancromwell** [comment]
I was able to print a label to a Dymo label printer.   The labels I am working with are height = 2.125 in and width = 1 in.  I'm using a template in SpineOMatic Cloud app with parsed call number and a layout that is set with my label height and width, portrait and 1 label per page.  I made sure the Dymo printer was selected in the print preview when attempting my print and then had to go into the "More Settings" on the preview and select "Page size" = 1 and 2 1/8 in and changed "Margins" = None.  

![label](https://user-images.githubusercontent.com/75325765/116815974-1c811900-ab2e-11eb-9f81-ef0d32e36eb9.png)

**Comment by MaggieMcGee** [comment]
Awesome! Thank you @dancromwell. I've been focused on the sheet labels and didn't get to this. I appreciate the detailed help.
Maggie

**Comment by dancromwell** [comment]
@MaggieMcGee no problem.  Hope it is helpful.

Daniel

**Comment by jweisman** [comment]
Good stuff @dancromwell . Thanks for sharing this!

**Comment by MaggieMcGee** [comment]
@dancromwell  and @jweisman 

Testing printing to a zebra printer. I cannot get the label to print higher up. I do not see where I can adjust the page size beyond 1 for Chrome. 

<img width="207" alt="spine_zebra" src="https://user-images.githubusercontent.com/81188041/121035149-9a62c080-c77b-11eb-99cb-25b87e3b3e10.png">

<img width="619" alt="spine_zebra2" src="https://user-images.githubusercontent.com/81188041/121035160-9cc51a80-c77b-11eb-80e3-93348b572e53.png">

Thanks,
Maggie

**Comment by HSteeleLTS** [comment]
Good morning.   This thread is very helpful in us considering how to configure how to configure our Zebra printer for spine label printing.

However we have an additional issue.  I'm not sure if this is the right place to forward things to development, but Ex Libris support sent me here.  The issue is our Zebra printer through its configuration settings file embedded in the printer requires there to be a pocket label in the label print job that is sent to the printer.  Both for workflow (it helps staff confirm they've scanned the right book) and because the label won't print without it, we need to be able to send the pocket label in data that is sent to the printer.  

It looks given current functionality in the SpineOMatic *cloud app* this feature isn't supported, given this documentation.  If this is the right place I wanted to forward this as an improvement for development, but in the meantime I wondered if anyone had a hack/workaround for this?  I've included snapshots of our settings and an image I was able to "hack" print with them

![-hacked-spine-pocket label](https://user-images.githubusercontent.com/44376066/121672288-a00f1d80-ca7d-11eb-8b7b-8840fd38c805.jpg)
<img width="960" alt="layout" src="https://user-images.githubusercontent.com/44376066/121672361-b4ebb100-ca7d-11eb-8856-e879f154b9fc.png">
<img width="960" alt="template" src="https://user-images.githubusercontent.com/44376066/121672381-bcab5580-ca7d-11eb-8e4b-da15bb836773.png">
