### ISSUE TITLE
Unable to use table format

### ISSUE THREAD

**Issue by mck1777** [ExLibrisGroup/spineomatic-cloudapp#62]
Greetings
I was asked by one of my libraries to print the label from the bottom up (they want the space at the top to use stickers). Thinking I should create a table to use this feature of the formatting aspect, I was going to insert a row with 8 cells. (our current label sheet is 8 across and 7 down). This lead me to look at the table formatting mentioned on https://github.com/ExLibrisGroup/spineomatic-cloudapp/wiki/Help#define-the-template.

Using the instructions on your documentation; I am unable to see the column proprieties, I can see the row properties. I have uploaded a mp4 to show you what I am doing. Am I trying to access properties incorrectly? Am I thinking correctly using the table feature will format the labels as this library wants?

Thank you 
Maryclare Koenig

https://user-images.githubusercontent.com/72558867/154129655-e1facffb-c789-4ccc-bc96-8730a9401ebf.mp4

**Comment by mgobat** [comment]
Hi @mck1777...

Unfortunately, "Column properties" are not an option in the editor. Rather, since it is a single row table, "Cell properties" should be used to set the height and width. I clearly see where the instructions imply "column properties". I will clarify the instructions.

Do you have more details about how the library wishes the labels to print? I can work with you to see if the tables can solve the problem.

-mark

**Comment by mgobat** [comment]
Closing due to lack of response.
