### ISSUE TITLE
How to remove extra line before c.2, combine text w/ space...

### ISSUE THREAD

**Issue by KatieLai** [ExLibrisGroup/spineomatic-cloudapp#86]
Hi, sorry I am quite stuck.  Could you please kindly advise how to fix these as shown in the screenshot below?  Fyi, we're using Alma's parsing routine 5.

1. There is an extra line between the copy ID and the volume no.  How do we remove it?
2. We have a hyphen as part of the call number (see the 4th call number).  Is there a way to remove unwanted punctuation within a call number? I see that we can do so in the downloaded program, but not sure how to do it in the cloudapp.
3. In the 5th call number, we have "st. gd."  Because of the space, it's broken into 2 separate lines.  Is there a way to connect it back so that "st. gd." appears in the same line?  Did SpineOmatic also drop my ending period?

<img width="477" alt="Screenshot 2022-08-03 at 4 42 55 PM" src="https://user-images.githubusercontent.com/110567414/182709449-6f0ad785-e6b1-4df7-8f55-c8a681b781c1.png">

Many thanks in advance!!

Cheers,
Katie

**Comment by mgobat** [comment]
@KatieLai, what call number field are you including in your template?  Do you have a "Call number parser" selected in the "Other options > Call number" section? If not, would any of the options there help?

Removing unwanted punctuation is an enhancement request.

**Comment by KatieLai** [comment]
Hi @mgobat

Here is the template I use. I selected: 

(1) "Parsed call number" and it changes it to "{{field:item_data.call_no}}".  Does it mean SpineOMatic is taking the item from the item record?  But then, the 7th call number in my previous screenshot is not showing the Item Call Number in the Item Record but the number in the bib/holdings.

<img width="343" alt="Screenshot 2022-08-04 at 12 03 55 PM" src="https://user-images.githubusercontent.com/110567414/182894882-cfa8cfaf-926b-4101-8932-3199eb271eea.png">

(2) Call Number Parser as "Default (Alma)"

<img width="274" alt="Screenshot 2022-08-04 at 12 07 13 PM" src="https://user-images.githubusercontent.com/110567414/182895229-c9793f3c-00df-4cad-97ef-65c161107036.png">

(3) Specifications for the Copy Number

<img width="242" alt="Screenshot 2022-08-04 at 12 04 14 PM" src="https://user-images.githubusercontent.com/110567414/182895414-030d261f-53a0-4027-8291-7d09d13c6d25.png">

- How about the extra empty line before the copy no. / volumn no.?  How do I remove them?
- And a follow-up to point (1), if I want SpineOMatic to print the Item Call Number instead of the call number from the bib/holdings record, what should I do?
- As for the enhancement request to remove unwanted punctuation, do I need to submit the request somewhere or a specific form to fill out?

Many thanks for your help!

Katie

**Comment by mgobat** [comment]
Thanks for these details, @KatieLai; I'll take a look.

- Some of the way the call number prints is due to the Alma Parser. Selecting "Default (Alma)" in the "Call Number Parser" dropdown defers to Alma's parsing. Selecting a different parser in the "Call Number Parser" dropdown can override some of Alma's parsing. Some of what you'd like may require new options in the "Call Number Parser" dropdown. I need to spend some time digging into this before I can say these are defects or enhancements.
- Including "Parsed call number" as a field in the template should be pulling the call number from the item record.
- I will create the enhancement for removing punctuation here on GitHub. You are welcome to create additional GitHub issues for other enhancements you'd like.

**Comment by mgobat** [comment]
@KatieLai, are you still having trouble with the empty line before copy no / volume no? You can edit the raw HTML for the template by clicking the <> icon in the toolbar, and replace the <p> tag with a <br> tag. I think that should fix it.
