### ISSUE TITLE
want to hide dot before Cutter no. like what desktop app can do

### ISSUE THREAD

**Issue by ClaireCLGUO** [ExLibrisGroup/spineomatic-cloudapp#88]
Desktop SpineOMatic can hide Cutter decimal, but there is no such settings could be made in cloud version.
![image](https://user-images.githubusercontent.com/110590074/182779640-357a5d78-db93-48d9-b1ae-a31be1b2028f.png)

**Comment by mgobat** [comment]
Available in v1.2.8.

**Comment by ClaireCLGUO** [comment]
After testing, it doesn't work perfectly. For call numbers of identical structure, one decimal is hided but another isn't.
![image](https://user-images.githubusercontent.com/110590074/191878387-b245bca1-925b-4ae5-9f0e-1b91f6c815c4.png)

**Comment by mgobat** [comment]
Thanks for testing, @ClaireCLGUO. We will take a look.

**Comment by mgobat** [comment]
@ClaireCLGUO, thanks for the additional details.

**Comment by mgobat** [comment]
@ClaireCLGUO, I think I have this fixed. I will publish a new version of the Cloud App on Monday, 09-January. I don't want to publish a new version right before the weekend.

**Comment by mgobat** [comment]
New version,v1.3.0, published on Monday, 09-January.

**Comment by mgobat** [comment]
@simonreadnz, do you have the decimal character set to "." in your template? If so, it is certainly possible that the code isn't working correctly for your call numbers.

**Comment by simonreadnz** [comment]
@mgobat I didn't have it configured but I do now :)

![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/38444724/dbb07a17-bcf9-452f-abaa-18bb87ae47d0)

I have two different variations of that call number in Alma (for holdings in different branches) but neither of them seems to work:

‡h BF76.7 ‡i .AG49 2010a
‡h BF76.7 .AG49 2010a

Another variation we might have is ‡h HF5415.12.A785 MA742 (so no space between the decimalised number and the cutter.

None of these variations seems to work at the moment - not sure if it's because of something further I haven't configured properly or if the functionality isn't working as intended.

Thanks!

**Comment by mgobat** [comment]
@simonreadnz, the SpineOMatic Cloud App defines the cutter to be the cutter decimal character, followed by a single alphabetic character, followed by a numeric character. It isn't finding your cutter since it is the decimal character followed by two alphabetic characters. Admittedly, I'm no call number expert. Is this cutter definition too limiting?

**Comment by simonreadnz** [comment]
@mgobat I've got the Line breaks between call number parts ticked and the Maximum call number parts are set to 30 (couldn't tell you why I set it to that - happy to change it to something else if that works). We're set to Parse routine 6 in Alma if that makes any difference for testing.

I've tried some other call numbers with just a single letter after the cutter decimal followed by a number but that didn't seem to work either. We have lots of call numbers with two letters after the cutter decimal and then followed by numbers, so if we could get it working we'd want to try to accommodate that scenario. I'm not sure how the desktop apps calculates it and if you could copy that logic?

Some more examples with a single character after the cutter decimal:

‡h PR9639.H84 M9 1982
PR
9639
.H84
M9
1982

‡h D843.KH2
D
843
.KH2

‡h HD70.U5 DS74
HD
70
.U5
DS74

@ClaireCLGUO did you ever get it to work with you call numbers?

**Comment by ClaireCLGUO** [comment]
@simonreadnz The dots are hided, the configuaration is below:
![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/110590074/30fe3772-3040-4f91-8373-9762c7260ce2)
However, we did not print labels using cloud or desktop SpineOmatic because the label size could not be adjusted to exactly match the paper size.

**Comment by simonreadnz** [comment]
Thanks @ClaireCLGUO Looks pretty similar to our setup except for the Maximum call number parts. Thanks for the heads up about the label sizes - we've haven't looked at that very closely yet

**Comment by mgobat** [comment]
@simonreadnz, let's try to figure out why call numbers with a single alphabetic after the cutter decimal aren't printing with the decimal removed before we make any changes to the logic.  There must be some difference in our settings as it is working for me.

Here are all my settings. Maybe you can point out what I have set differently than you.

Call number parsing setting in Alma:
<img width="695" alt="parse-routine-alma" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/e119cd78-4bee-44d4-97dd-652f5d7d97c1">


Bib/holdings MARC records:
<img width="622" alt="marc-alma" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/a10acfae-4231-4b2b-b8df-44432ef3d18f">


"Call number" options in my SpineOMatic Cloud App template:
<img width="281" alt="template-callnumber" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/ee4d5485-a304-4051-a2a5-d046ad8b33a8">


And the generated label:
<img width="277" alt="label" src="https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/45852490/87194267-59e0-4047-913e-b93bdd597ec4">

For reference, my template is pretty basic. Here's the source code:
`<p>{{field:item_data.call_no}} <br />
{{field:holding_data.copy_id}} <br />
{{field:item_data.barcode}}</p>
`

The logic difference between the SpineOMatic Windows application and the Cloud App is that the Windows application looks for the cutter decimal followed by at least one alphabetic character; it doesn't check beyond that.

**Comment by simonreadnz** [comment]
@mgobat Thanks! I can see the problem now - I've been using the Parsed call number part one, two three etc. fields rather than just the Parsed call number field. I've changed it over and now the cutter decimal is being removed where there is one letter after the decimal. The only outstanding issue I can see is where there are two letters after the cutter decimal then the cutter decimal still shows (as previously discussed).

Good progress!

![image](https://github.com/ExLibrisGroup/spineomatic-cloudapp/assets/38444724/577c4e50-258b-4d5e-bc21-8f7ddffbda3e)

**Comment by simonreadnz** [comment]
@mgobat I think it'd be OK to loosen the rule to say a decimal followed by one or more alpha characters would work OK. The main thing is that the decimal isn't followed immediately by a digit. I believe we only have one or two alpha characters after the decimal so the criteria could be limited to look for up to two alpha characters followed by a digit but I'm inclined to think it's not necessary to be that restrictive - specifying one or more alpha characters after the decimal should be adequate.

**Comment by mgobat** [comment]
New release, v1.3.5, now defines the cutter to be the decimal character, followed by an alphabetic, then followed by either an alphabetic or a digit.

**Comment by simonreadnz** [comment]
Thanks @mgobat - it's looking good!
