### ISSUE TITLE
Future of label templates question

### ISSUE THREAD

**Issue by kronneCSU** [ExLibrisGroup/spineomatic-cloudapp#96]
Hi. I've been testing this app out at my library and am wondering if there are any plans to add more premade label templates for this? For example, I use a specific DEMCO brand label that allows for a spine label and a pocket label, so having the ability to either select or import the template for those specific labels would make it a lot easier to get the formatting correct.

**Comment by mgobat** [comment]
@kronneCSU, we'll treat this as an enhancement request. Could you please add the details about the labels you are using? Thank you.

**Comment by kronneCSU** [comment]
This is the specific product I use, it includes Word templates, but that doesn't always translate to other programs. 

https://www.demco.com/demco-reg-gaylord-reg-processing-circulation-label-sets-1-14-x-2-58?simpleProduct=49550

I hope that helps? Let me know if there is other information I can provide.

**Comment by mgobat** [comment]
@kronneCSU, I'm doing some experimenting with this issue. Could you provide me with the fields you'd want included in both the smaller and larger label pair? Thank you.

**Comment by kronneCSU** [comment]
The small label would only be the LC call # and a location. The large label has the title, the description from the description field, our library name, and the date the item was received. I could send you an image of how that formats, or I could share how we currently have the settings in our desktop Spine O Matic program set up if that would help.

Thanks,
Kristina Ronne
She/her/hers

Print & Electronic Resources Assistant
Acquisitions and Metadata Services
Colorado State University Libraries

P: 970-491-1073
1019 Campus Delivery | Fort Collins, CO 80523

[Libraries-Logo-for-Email-Signatures-Left-Aligned]

**Comment by mgobat** [comment]
@kronneCSU, sure the desktop app settings wouldn't hurt, and a sample image would be nice, too. Thank you.

**Comment by kronneCSU** [comment]
Hello,

I have attached the sample of how the labels print, and our current desktop settings.

Thanks for looking into this.

Kristina Ronne
She/her/hers

Print & Electronic Resources Assistant
Acquisitions and Metadata Services
Colorado State University Libraries

P: 970-491-1073
1019 Campus Delivery | Fort Collins, CO 80523

[Libraries-Logo-for-Email-Signatures-Left-Aligned]

**Comment by mgobat** [comment]
@kronneCSU, I'm not seeing the attachments; not sure what's up with that.

I've made an attempt at this. I don't have a sample label sheet, so I'm basing things off the Microsoft Word template. I've attached a PDF (the test.pdf link below) with sample output. Could you please print it and lay it on top of one of your label sheets and let me know if I'm anywhere close? I've left some of the border lines visible to help with lining things up. It looks pretty good when I lay a printout of the test against a printout of the Microsoft Word template, although I had to set custom margins before sending the preview to the printer. Thanks.

[test.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10180275/test.pdf)

**Comment by kronneCSU** [comment]
Here, I've tried attaching them another way.

[SpineOMatic settings for Journal Label printing.docx](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10180315/SpineOMatic.settings.for.Journal.Label.printing.docx)
[Periodical Labels Example.pdf](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10180317/Periodical.Labels.Example.pdf)

**Comment by mgobat** [comment]
@kronneCSU, yes, I see them this time. Thank you!

**Comment by mgobat** [comment]
@kronneCSU, I've had the best luck with the following layout settings:

![issue96-layout](https://user-images.githubusercontent.com/45852490/206551874-d97a3a4d-4c58-4dd9-aca6-b3fb53c1d272.png)

Of course, these tend to be printer specific. My results weren't as good using the settings you used in the SpineOMatic Windows application.

Then for the template, look at the attached file, issue96-template.txt. There is a version with borders and one without. You'll need to change the included fields to the ones you really want to use. Just edit your own copy of the file as needed with the correct fields. Then create a new template in the Cloud App, click the "<>" icon in the template editing toolbar, and paste your version of the template. Remember that the second column in the template is the gap between the smaller and larger labels and should not contain any fields.  

Again, I've based this off the Microsoft Word template since I don't have any of the label stock. Curious if this gets you close.... or not.

[issue96-template.txt](https://github.com/ExLibrisGroup/spineomatic-cloudapp/files/10189026/issue96-template.txt)
